# Generated by Django 3.1.7 on 2021-05-03 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pastel', models.BooleanField(blank=True)),
                ('forma', models.TextField(choices=[('CI', 'Circular'), ('CU', 'Cuadrado')])),
                ('num_pisos', models.IntegerField(blank=True)),
                ('porciones', models.IntegerField(blank=True)),
                ('masa', models.CharField(choices=[('VA', 'Vainilla'), ('CH', 'Chocolate'), ('TL', 'Tres Leches'), ('RV', 'RedVelvet')], max_length=2)),
                ('relleno', models.CharField(choices=[('AQ', 'Arequipe'), ('NU', 'Nutella'), ('ML', 'Mermelada'), ('CP', 'CremaPastelera')], max_length=2)),
                ('Cobertura', models.CharField(choices=[('CR', 'Crema'), ('FD', 'Fondant')], max_length=2)),
                ('ColorCobertura', models.CharField(choices=[('AZ', 'Azul'), ('AM', 'Amarillo'), ('BL', 'Amarillo'), ('VD', 'Verde'), ('RJ', 'Rojo')], max_length=2)),
                ('costo', models.FloatField(blank=True, default=0)),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('costo', models.FloatField(blank=True)),
                ('status', models.BooleanField(blank=True)),
                ('correo_asociado', models.EmailField(max_length=255)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=255)),
                ('pasteles', models.ManyToManyField(to='pedido.Pastel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
